Improve the validation that the arguments are actually arguments

diff --git a/dupro b/dupro
--- a/dupro
+++ b/dupro
@@ -25,6 +25,15 @@ function die() {
 	exit 1
 }
 
+function is_argument() {
+	ARG="$1"
+	if [ -z "$ARG" -o "${ARG:0:1}" = '-' ]; then
+		# This is empty, or looks like an option, so return false.
+		return 1
+	fi
+	return 0
+}
+
 # Create and/or reset permissions on the ~/.dupro directory.
 USER_PROFILE_DIR="$HOME/.dupro"
 if [ ! -e "$USER_PROFILE_DIR" ]; then
@@ -38,6 +47,11 @@ if [ "$#" -lt 2 ]; then
 	die "Not enough arguments."
 fi
 
+if ! is_argument "$1" || ! is_argument "$2"; then
+	show_usage
+	die "The first 2 arguments must not be options."
+fi
+
 # Get arguments and options.
 PROFILE="$1"; shift;
 COMMAND="$1"; shift;
@@ -45,6 +59,10 @@ COMMAND="$1"; shift;
 case $COMMAND in
 	restore|remove-*)
 		EXTRA_ARGUMENT="$1"; shift;
+		if !  is_argument "$EXTRA_ARGUMENT"; then
+			show_usage
+			die "With the $COMMAND command, the 3rd argument is required and must not be an option."
+		fi
 		;;
 esac
 EXTRA_OPTIONS="$@"
@@ -87,21 +105,10 @@ case $COMMAND in
 		;;
 
 	restore)
-		# Validate the restore target.
-		if [ -z "$EXTRA_ARGUMENT" -o "${EXTRA_ARGUMENT:0:2}" = '--' ]; then
-			show_usage
-			die "When restoring, the 3rd argument must be the target directory to restore files to."
-		fi
-
 		exec duplicity restore $DUPLICITY_OPTIONS $EXTRA_OPTIONS $TARGET $EXTRA_ARGUMENT
 		;;
 
 	remove-*)
-		if [ -z "$EXTRA_ARGUMENT" -o "${EXTRA_ARGUMENT:0:2}" = '--' ]; then
-			show_usage
-			die "When removing, the 3rd argument must be a time or a count."
-		fi
-
 		exec duplicity $COMMAND $EXTRA_ARGUMENT $DUPLICITY_OPTIONS $EXTRA_OPTIONS $TARGET
 		;;
 
